# Generated by Django 5.1.2 on 2024-10-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_toko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
