# Generated by Django 5.1.2 on 2024-10-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_toko', '0002_alter_makanan_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makanan',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makanan',
            name='links',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makanan',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makanan',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makanan',
            name='rating_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makanan',
            name='services',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
