# Generated by Django 5.1.2 on 2024-10-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_toko', '0003_alter_makanan_address_alter_makanan_latitude_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Makanan',
            new_name='Restaurant',
        ),
    ]
