# Generated by Django 5.1.2 on 2024-10-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_toko', '0005_alter_restaurant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
