# Generated by Django 5.1.2 on 2024-10-26 20:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriterestaurant',
            unique_together={('user', 'restaurant')},
        ),
    ]
