# Generated by Django 5.1.2 on 2024-10-26 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_toko', '0004_rename_makanan_restaurant'),
        ('favorites', '0002_alter_favoriterestaurant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantreview',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daftar_toko.restaurant'),
        ),
        migrations.AlterField(
            model_name='favoriterestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daftar_toko.restaurant'),
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
