# Generated by Django 5.1.2 on 2024-10-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_remove_restaurant_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='operating_hours',
            new_name='opening_hours',
        ),
        migrations.AlterUniqueTogether(
            name='favoriterestaurant',
            unique_together={('restaurant',)},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='halal_status',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='user',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='links',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='services',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='favoriterestaurant',
            name='user',
        ),
    ]
