# Generated by Django 5.1.2 on 2024-10-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_rename_operating_hours_restaurant_opening_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='opening_hours',
            new_name='operating_hours',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='links',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rating_amount',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='services',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='halal_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
