# Generated by Django 5.1.2 on 2024-10-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_alter_restaurantreview_restaurant_and_more'),
        ('favorites', '0004_rename_opening_hours_restaurant_operating_hours_and_more'),
    ]

    operations = [
    ]
