# Generated by Django 5.1.2 on 2024-10-27 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0005_merge_20241027_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('halal_status', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_hours', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='favoriterestaurant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favoriterestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorites.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorites.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriterestaurant',
            unique_together={('restaurant',)},
        ),
    ]
