# Generated by Django 5.1.2 on 2024-10-27 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_toko', '0006_alter_restaurant_id'),
        ('favorites', '0006_restaurant_alter_favoriterestaurant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daftar_toko.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daftar_toko.restaurant'),
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
