# Generated by Django 5.1.2 on 2024-10-27 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_last_login'),
        ('daftar_toko', '0006_alter_restaurant_id'),
        ('favorites', '0007_alter_favoriterestaurant_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriterestaurant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favoriterestaurant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriterestaurant',
            unique_together={('user', 'restaurant')},
        ),
    ]
