# Generated by Django 5.1.2 on 2024-10-25 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
