# Generated by Django 5.1.2 on 2024-11-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0004_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
