# Generated by Django 5.1.2 on 2024-12-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0005_delete_recipe'),
        ('about_me', '0007_alter_recipe_profile'),
    ]

    operations = [
    ]
