# Generated by Django 5.1.4 on 2024-12-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0007_alter_recipe_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
