# Generated by Django 5.1.2 on 2024-10-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('adminXYZ123!@#', 'Admin'), ('userABC987$%^', 'User')], default='userABC987$%^', max_length=20),
        ),
    ]
