# Generated by Django 5.1.2 on 2024-10-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_image_alter_user_username'),
        ('authentication', '0003_alter_user_image_alter_user_role_alter_user_username'),
    ]

    operations = [
    ]
